CREATE (Thomas:Person {name:'Thomas'})
CREATE (Alfie:Person {name:'Alfie'})
CREATE (Jack:Person {name:'Jack'})
CREATE (Jacob:Person {name:'Jacob'})
CREATE (Oliver:Person {name:'Oliver'})
CREATE (Harry:Person {name:'Harry'})
CREATE (James:Person {name:'James'})
CREATE (William:Person {name:'William'})
CREATE (George:Person {name:'George'})
CREATE (Joshua:Person {name:'Joshua'})
CREATE (Daniel:Person {name:'Daniel'})
CREATE (Joseph:Person {name:'Joseph'})
CREATE (Ethan:Person {name:'Ethan'})
CREATE (Archie:Person {name:'Archie'})
CREATE (Oscar:Person {name:'Oscar'})
CREATE (Chloe:Person {name:'Chloe'})
CREATE (Orla:Person {name:'Orla'})
CREATE (Courtney:Person {name:'Courtney'})
CREATE (Jessie:Person {name:'Jessie'})
CREATE (Ella:Person {name:'Ella'})
CREATE (Kelly:Person {name:'Kelly'})
CREATE (Dorothy:Person {name:'Dorothy'})
CREATE (Mae:Person {name:'Mae'})
CREATE (Jane:Person {name:'Jane'})
CREATE (Ann:Person {name:'Ann'})
CREATE (Francis:Person {name:'Francis'})
CREATE (Maisie:Person {name:'Maisie'})
CREATE (Phoebe:Person {name:'Phoebe'})
CREATE (Yasmine:Person {name:'Yasmine'})
CREATE (Carmen:Person {name:'Carmen'})
CREATE (Sophia:Person {name:'Sophia'})
CREATE (Kara:Person {name:'Kara'})
CREATE (Joan:Person {name:'Joan'})
CREATE (Nia:Person {name:'Nia'})
CREATE (Alfie)-[:FRIENDS_WITH]->(Thomas)
CREATE (Jack)-[:FRIENDS_WITH]->(Thomas)
CREATE (Jacob)-[:FRIENDS_WITH]->(Thomas)
CREATE (Oliver)-[:FRIENDS_WITH]->(Thomas)
CREATE (Harry)-[:FRIENDS_WITH]->(Thomas)
CREATE (James)-[:FRIENDS_WITH]->(Thomas)
CREATE (William)-[:FRIENDS_WITH]->(Thomas)
CREATE (George)-[:FRIENDS_WITH]->(Thomas)
CREATE (Daniel)-[:FRIENDS_WITH]->(Thomas)
CREATE (Joseph)-[:FRIENDS_WITH]->(Thomas)
CREATE (Ethan)-[:FRIENDS_WITH]->(Thomas)
CREATE (Archie)-[:FRIENDS_WITH]->(Thomas)
CREATE (Courtney)-[:FRIENDS_WITH]->(Thomas)
CREATE (Ella)-[:FRIENDS_WITH]->(Thomas)
CREATE (Dorothy)-[:FRIENDS_WITH]->(Thomas)
CREATE (Kara)-[:FRIENDS_WITH]->(Thomas)
CREATE (Jack)-[:FRIENDS_WITH]->(Alfie)
CREATE (Jacob)-[:FRIENDS_WITH]->(Alfie)
CREATE (William)-[:FRIENDS_WITH]->(Alfie)
CREATE (Archie)-[:FRIENDS_WITH]->(Alfie)
CREATE (Courtney)-[:FRIENDS_WITH]->(Alfie)
CREATE (Ella)-[:FRIENDS_WITH]->(Alfie)
CREATE (Dorothy)-[:FRIENDS_WITH]->(Alfie)
CREATE (Sophia)-[:FRIENDS_WITH]->(Alfie)
CREATE (Jacob)-[:FRIENDS_WITH]->(Jack)
CREATE (William)-[:FRIENDS_WITH]->(Jack)
CREATE (George)-[:FRIENDS_WITH]->(Jack)
CREATE (Joshua)-[:FRIENDS_WITH]->(Jack)
CREATE (Archie)-[:FRIENDS_WITH]->(Jack)
CREATE (Phoebe)-[:FRIENDS_WITH]->(Jack)
CREATE (Yasmine)-[:FRIENDS_WITH]->(Jack)
CREATE (Joan)-[:FRIENDS_WITH]->(Jack)
CREATE (William)-[:FRIENDS_WITH]->(Jacob)
CREATE (Ethan)-[:FRIENDS_WITH]->(Jacob)
CREATE (Archie)-[:FRIENDS_WITH]->(Jacob)
CREATE (James)-[:FRIENDS_WITH]->(Oliver)
CREATE (Daniel)-[:FRIENDS_WITH]->(Oliver)
CREATE (James)-[:FRIENDS_WITH]->(Harry)
CREATE (Daniel)-[:FRIENDS_WITH]->(Harry)
CREATE (Orla)-[:FRIENDS_WITH]->(Harry)
CREATE (Orla)-[:FRIENDS_WITH]->(James)
CREATE (Sophia)-[:FRIENDS_WITH]->(George)
CREATE (Joan)-[:FRIENDS_WITH]->(George)
CREATE (Nia)-[:FRIENDS_WITH]->(George)
CREATE (Nia)-[:FRIENDS_WITH]->(Joshua)
CREATE (Nia)-[:FRIENDS_WITH]->(Archie)
CREATE (Joan)-[:FRIENDS_WITH]->(Oscar)
CREATE (Nia)-[:FRIENDS_WITH]->(Oscar)
CREATE (Joan)-[:FRIENDS_WITH]->(Chloe)
CREATE (Nia)-[:FRIENDS_WITH]->(Chloe)
CREATE (Joan)-[:FRIENDS_WITH]->(Jessie)
CREATE (Nia)-[:FRIENDS_WITH]->(Jessie)
CREATE (Nia)-[:FRIENDS_WITH]->(Ella)
CREATE (Joan)-[:FRIENDS_WITH]->(Kelly)
CREATE (Nia)-[:FRIENDS_WITH]->(Kelly)
CREATE (Joan)-[:FRIENDS_WITH]->(Mae)
CREATE (Nia)-[:FRIENDS_WITH]->(Mae)
CREATE (Francis)-[:FRIENDS_WITH]->(Jane)
CREATE (Phoebe)-[:FRIENDS_WITH]->(Jane)
CREATE (Carmen)-[:FRIENDS_WITH]->(Jane)
CREATE (Joan)-[:FRIENDS_WITH]->(Jane)
CREATE (Nia)-[:FRIENDS_WITH]->(Jane)
CREATE (Francis)-[:FRIENDS_WITH]->(Ann)
CREATE (Phoebe)-[:FRIENDS_WITH]->(Ann)
CREATE (Kara)-[:FRIENDS_WITH]->(Ann)
CREATE (Kara)-[:FRIENDS_WITH]->(Francis)
CREATE (Carmen)-[:FRIENDS_WITH]->(Maisie)
CREATE (Nia)-[:FRIENDS_WITH]->(Maisie)
CREATE (Nia)-[:FRIENDS_WITH]->(Phoebe)
CREATE (Kara)-[:FRIENDS_WITH]->(Yasmine)
CREATE (Nia)-[:FRIENDS_WITH]->(Yasmine)
CREATE (Joan)-[:FRIENDS_WITH]->(Carmen)
CREATE (Nia)-[:FRIENDS_WITH]->(Carmen)
CREATE (Joan)-[:FRIENDS_WITH]->(Sophia)
CREATE (Nia)-[:FRIENDS_WITH]->(Sophia)
CREATE (Joan)-[:FRIENDS_WITH]->(Kara)
CREATE (Nia)-[:FRIENDS_WITH]->(Kara)
CREATE (Nia)-[:FRIENDS_WITH]->(Joan)
